# Generated by Django 3.1.6 on 2021-03-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Phone', models.CharField(max_length=10, null=True)),
                ('Email', models.CharField(max_length=100, null=True)),
                ('Date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
