# Generated by Django 3.1.6 on 2021-03-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210310_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Tags',
        ),
        migrations.AddField(
            model_name='products',
            name='Tags',
            field=models.ManyToManyField(to='accounts.Tag'),
        ),
    ]
